version: '2.1'

services:
  localstack:
    image: localstack/localstack-full
    ports:
      # dynamodb
      - "4569:4569"

      - "4564:4564"
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOTE_DOCKER=false
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"