

service: api-management

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221


  apiGateway:
    apiKeys:
      - free: ${file(./default-customers.js):private}
      - paid: 
        - myPaidKey
        - zezinho@ze.com
    usagePlan:
      - free:
          quota:
            limit: 5
            period: MONTH
          throttle:
            burstLimit: 200
            rateLimit: 200
      - paid:
          quota:
            limit: 1000
            period: DAY
          throttle:
            burstLimit: 400
            rateLimit: 50

package:
  excludeDevDependencies: true

plugins:
  - serverless-offline


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          private: true

