

service: tooling-s3-sqs

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-localstack
  - serverless-mocha-plugin
  - serverless-offline

custom:
  configValidationMode: off
  serverless-offline:
    useChildProcesses: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
        method: 'get'
        path: 'hello'


