

service: vpc-aurora-sql

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221


plugins:
  - serverless-offline

package:
  excludeDevDependencies: true

functions:
  hello:
    handler: src/index.handler
    events:
      - http:
          method: any
          path: hello
